---
title: "Add Behavior with Instance Methods"
type: "article"
description: "Create instance methods to add function to your objects"
tags: "instance-methods, variables, instance-variables, getters, setters"
---
