# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37acd645595ea643f7eef0c41ebc24862ecb57c5a45b063f4614d2e663284495902a3cef8d48d84fe25dcf99fa649174e364d8c017701751b8f73c9099fd90b9

test:
  secret_key_base: 339810328e64e352d856fe421b0eb8c0239fdc1c820885825a0d74d6ff88abbffde71bb6c498a63ce09b2473b72b2dee5d326f46de22c2d175b2bc514225d81e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
