---
title: "GitHub Pull Request Workflow"
type: "article"
description: "Describes how we can use GitHub Pull Requests to make changes to our codebase and facilitate code reviews."
tags: "git, github, pull-request"
