---
title: "Javascript: Basics of Functions"
type: "article"
visibility: "onsite"
description: "A discussion around functions in Javascript"
tags: "javascript, programming, web, client-side, functions, closures"
