---
title: "Word Counter"
type: "challenge"
description: "Print out the most common words in a file."
tags: "ruby, hashes, arrays"
ignore:
- "word-counter.md"
- "poe_usher.txt"
- "verne_80_days.txt"
- "shelley_frankie.txt"
- "stop_words.txt"
