---
title: "Palindrome Checker"
type: "challenge"
description: "Use Ruby to determine if a string is a palindrome"
depends: "rock-paper-scissors"
visibility: "onsite"
ignore:
- "evening-exercise-ruby-palindrome.md"
