---
title: "Speaking Engagements"
type: "challenge"
visibility: "subscribe"
description: "Use 2 dimensional array to manage a speaking schedule"
tags: "arrays, hashes, compound data structures"
---


